"""
SpikeExtensionEmitter
=====================
Generates a complete Spike ISA simulator extension plugin for all
proposed custom instructions.

The generated plugin is a self-contained directory that can be compiled
and loaded into Spike via --extension=<path_to_so>.

Output structure:
  spike_extension/
  ├── CMakeLists.txt
  ├── README.md
  ├── extension.cc          # Plugin entry point
  ├── insns/
  │   ├── vdotacc.h
  │   ├── mmtile.h
  │   ├── sfmax.h
  │   └── ...
  └── tests/
      └── test_<mnemonic>.S # RISC-V assembly test for each instruction
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

from riscv_cisg.analyzer.hotspot_detector import HotspotResult
from riscv_cisg.proposer.custom_instruction import CustomInstruction

logger = logging.getLogger(__name__)


class SpikeExtensionEmitter:
    """
    Emits a Spike ISA simulator plugin for all proposed custom instructions.

    Parameters
    ----------
    output_dir : str or Path
        Root directory for the generated plugin.
    workload_name : str
        Name used in README and CMakeLists.
    """

    def __init__(
        self,
        output_dir: str = "./output/spike_extension",
        workload_name: str = "transformer_workload",
    ):
        self.output_dir = Path(output_dir)
        self.workload_name = workload_name

    def emit(
        self, proposals: List[Tuple[HotspotResult, CustomInstruction]]
    ) -> List[Path]:
        """
        Generate the full Spike extension plugin.
        Returns list of generated file paths.
        """
        insns_dir = self.output_dir / "insns"
        tests_dir = self.output_dir / "tests"
        insns_dir.mkdir(parents=True, exist_ok=True)
        tests_dir.mkdir(parents=True, exist_ok=True)

        generated: List[Path] = []
        mnemonics = []
        seen_mnemonics: set = set()

        for hotspot, instr in proposals:
            safe_mnem = instr.mnemonic.replace(".", "_")
            if safe_mnem in seen_mnemonics:
                continue
            seen_mnemonics.add(safe_mnem)
            mnemonics.append(safe_mnem)

            # Write instruction header
            h_path = insns_dir / f"{safe_mnem}.h"
            h_path.write_text(instr.spike_extension_snippet, encoding="utf-8")
            generated.append(h_path)

            # Write assembly test
            test_path = tests_dir / f"test_{safe_mnem}.S"
            test_path.write_text(self._make_asm_test(instr), encoding="utf-8")
            generated.append(test_path)

        # Write extension.cc
        ext_path = self.output_dir / "extension.cc"
        ext_path.write_text(self._make_extension_cc(mnemonics), encoding="utf-8")
        generated.append(ext_path)

        # Write CMakeLists.txt
        cmake_path = self.output_dir / "CMakeLists.txt"
        cmake_path.write_text(self._make_cmake(mnemonics), encoding="utf-8")
        generated.append(cmake_path)

        # Write README
        readme_path = self.output_dir / "README.md"
        readme_path.write_text(self._make_readme(proposals), encoding="utf-8")
        generated.append(readme_path)

        # Write Makefile (alternative build)
        makefile_path = self.output_dir / "Makefile"
        makefile_path.write_text(self._make_makefile(), encoding="utf-8")
        generated.append(makefile_path)

        logger.info(
            "Spike extension: emitted %d files to %s", len(generated), self.output_dir
        )
        return generated

    # ------------------------------------------------------------------
    # Private: file generators
    # ------------------------------------------------------------------

    def _make_extension_cc(self, mnemonics: List[str]) -> str:
        includes = "\n".join(f'#include "insns/{m}.h"' for m in mnemonics)
        register_stmts = "\n".join(
            f"  register_insn(MATCH_{m.upper()}, MASK_{m.upper()}, "
            f"insn_{m}_impl);"
            for m in mnemonics
        )
        return f"""\
//===-- extension.cc - Custom RISC-V ISA Extension Plugin --===//
//
// Auto-generated by RISC-V CISG
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Workload:  {self.workload_name}
//
// Build:
//   mkdir build && cd build
//   cmake .. -DSPIKE_ROOT=/path/to/spike/install
//   make
//
// Run:
//   spike --extension=./libcisg_extension.so <your_elf>
//
//===----------------------------------------------------------------------===//

#include "spike/extension.h"
#include "spike/decode.h"
#include "spike/processor.h"

{includes}

// ─────────────────────────────────────────────────────────────
// Encoding masks (must match TableGen definitions exactly)
// ─────────────────────────────────────────────────────────────
{"".join(self._encoding_macros(m) for m in mnemonics)}

// ─────────────────────────────────────────────────────────────
// Extension registration
// ─────────────────────────────────────────────────────────────
struct cisg_extension_t : extension_t {{
  const char* name() override {{ return "cisg"; }}

  std::vector<insn_desc_t> get_instructions() override {{
    std::vector<insn_desc_t> insns;
{register_stmts}
    return insns;
  }}

  std::vector<disasm_insn_t*> get_disasms() override {{
    std::vector<disasm_insn_t*> out;
    // Add disassembly entries here for each instruction
    return out;
  }}
}};

// Plugin entry point — Spike calls this function to load the extension
REGISTER_EXTENSION(cisg, []() {{ return new cisg_extension_t; }})
"""

    def _encoding_macros(self, mnemonic: str) -> str:
        # Placeholder macros — in practice derived from actual encoding
        upper = mnemonic.upper()
        return (
            f"#define MATCH_{upper}   0x00000000U  // TODO: fill from TableGen\n"
            f"#define MASK_{upper}    0xFE00707FU  // TODO: fill from TableGen\n\n"
        )

    def _make_cmake(self, mnemonics: List[str]) -> str:
        return f"""\
cmake_minimum_required(VERSION 3.16)
project(cisg_extension LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)

# ── Spike headers ──────────────────────────────────────────────
# Set SPIKE_ROOT to your Spike installation prefix
# e.g.: cmake .. -DSPIKE_ROOT=$HOME/.local
if(NOT DEFINED SPIKE_ROOT)
  set(SPIKE_ROOT "/usr/local" CACHE PATH "Spike install prefix")
endif()

include_directories(${{SPIKE_ROOT}}/include)
include_directories(${{SPIKE_ROOT}}/include/riscv)
include_directories(${{CMAKE_CURRENT_SOURCE_DIR}})

# ── Shared library ─────────────────────────────────────────────
add_library(cisg_extension SHARED
  extension.cc
)

target_compile_options(cisg_extension PRIVATE
  -O2 -Wall -Wextra
  -fPIC
)

# ── Install ────────────────────────────────────────────────────
install(TARGETS cisg_extension
  LIBRARY DESTINATION lib
)

# ── Tests ──────────────────────────────────────────────────────
# Uncomment to enable assembly-level tests (requires riscv64-unknown-elf-gcc)
# enable_testing()
# foreach(test {' '.join(mnemonics)})
#   add_test(NAME test_${{test}}
#     COMMAND spike --extension=$<TARGET_FILE:cisg_extension>
#             tests/test_${{test}}.elf)
# endforeach()
"""

    def _make_makefile(self) -> str:
        return """\
# Alternative GNU Make build for Spike extension
# Usage: SPIKE_ROOT=/path/to/spike make

SPIKE_ROOT ?= /usr/local
CXX        ?= g++
CXXFLAGS   := -O2 -Wall -std=c++17 -fPIC \\
              -I$(SPIKE_ROOT)/include \\
              -I$(SPIKE_ROOT)/include/riscv \\
              -I.

TARGET := libcisg_extension.so

all: $(TARGET)

$(TARGET): extension.cc
\t$(CXX) $(CXXFLAGS) -shared -o $@ $<

clean:
\trm -f $(TARGET)

.PHONY: all clean
"""

    def _make_asm_test(self, instr: CustomInstruction) -> str:
        safe_mnem = instr.mnemonic.replace(".", "_")
        # Use .insn directive as universal fallback for custom encodings
        opcode = instr.opcode_space.value
        f3 = instr.funct3
        f7 = instr.funct7

        return f"""\
# ===-- test_{safe_mnem}.S - Assembly Test for {instr.mnemonic.upper()} --===
#
# Tests the {instr.mnemonic} custom instruction in Spike.
# Build:
#   riscv64-unknown-elf-gcc -march=rv64imfd -o test_{safe_mnem}.elf test_{safe_mnem}.S
# Run:
#   spike --extension=./libcisg_extension.so test_{safe_mnem}.elf

.section .data
input_a:  .float 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0
input_b:  .float 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
output:   .skip 64

.section .text
.global _start
_start:
    # Load input pointers
    la      a0, input_a
    la      a1, input_b
    la      a2, output
    li      a3, 8             # vector length

    # Emit custom instruction using .insn directive
    # Format: .insn <fmt>, <opcode>, <operands>
    # opcode=0x{opcode:02X}, funct3=0x{f3:01X}, funct7=0x{f7:02X}
    .insn r 0x{opcode:02X}, 0x{f3:01X}, 0x{f7:02X}, a2, a0, a1

    # Verify: write result to tohost for Spike's htif
    li      a7, 93            # SYS_exit
    li      a0, 0             # exit code 0 = pass
    ecall

.size _start, . - _start
"""

    def _make_readme(
        self, proposals: List[Tuple[HotspotResult, CustomInstruction]]
    ) -> str:
        instr_docs = []
        for hotspot, instr in proposals:
            speedup = (
                f"{instr.speedup_model.estimated_speedup:.1f}x"
                if instr.speedup_model
                else "N/A"
            )
            instr_docs.append(f"""
### `{instr.mnemonic}`

**Accelerates:** `{instr.target_op_type}`
**Estimated speedup:** {speedup}
**Encoding:** `{instr.encoding_summary}`
**Assembly:** `{instr.asm_syntax}`

{instr.description}

**Semantics:**
```c
{instr.semantics_pseudocode}
```
""")

        return f"""\
# CISG Spike Extension — {self.workload_name}

Auto-generated by [RISC-V CISG](https://github.com/your-username/riscv-cisg)

## Overview

This Spike ISA simulator extension implements {len(proposals)} custom RISC-V
instruction(s) proposed to accelerate the `{self.workload_name}` workload.

## Prerequisites

- [Spike RISC-V ISA Simulator](https://github.com/riscv-software-src/riscv-isa-sim) (≥1.1.0)
- C++17-capable compiler (GCC ≥ 9 or Clang ≥ 10)
- CMake ≥ 3.16 (or GNU Make)

## Build

```bash
# Clone Spike (if not already installed)
git clone https://github.com/riscv-software-src/riscv-isa-sim
cd riscv-isa-sim && mkdir build && cd build
../configure --prefix=$HOME/.local
make install

# Build this extension
cd /path/to/spike_extension
mkdir build && cd build
cmake .. -DSPIKE_ROOT=$HOME/.local
make
```

## Usage

```bash
# Run a RISC-V ELF with the custom extension loaded
spike --extension=./build/libcisg_extension.so your_program.elf

# Or with the Makefile build
spike --extension=./libcisg_extension.so your_program.elf
```

## Instructions

{"".join(instr_docs)}

## Integration with LLVM

See the `../tablegen/` directory for the corresponding LLVM TableGen definitions.

## License

MIT
"""
