"""
TableGenEmitter
===============
Generates complete LLVM TableGen files for integrating custom RISC-V
instructions into the LLVM RISC-V backend.

Output files:
  - RISCVInstrInfoCustom.td   : instruction definitions
  - RISCVCustomInstrPatterns.td : ISel patterns (optional)
  - CMakeLists.patch           : build system integration note

Usage:
  emitter = TableGenEmitter(output_dir="./output/tablegen")
  emitter.emit(proposals)
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

from riscv_cisg.analyzer.hotspot_detector import HotspotResult
from riscv_cisg.proposer.custom_instruction import CustomInstruction

logger = logging.getLogger(__name__)

_HEADER = """\
//===-- {filename} - RISC-V Custom Instruction Definitions --===//
//
// Auto-generated by RISC-V CISG (Custom Instruction Suggestion Generator)
// Generated: {timestamp}
// Target workload: {workload_name}
//
// This file defines custom RISC-V ISA extensions suggested for the
// given ML workload. Integrate into the LLVM RISC-V backend as follows:
//
//   1. Copy this file to: llvm/lib/Target/RISCV/
//   2. Add to RISCVInstrInfo.td:  include "RISCVInstrInfoCustom.td"
//   3. Rebuild LLVM with: cmake --build . --target llc
//
// RISC-V custom opcode spaces used:
//   custom-0: 0x0B  custom-1: 0x2B  custom-2: 0x5B  custom-3: 0x7B
//===----------------------------------------------------------------------===//

include "RISCVInstrFormats.td"

"""


class TableGenEmitter:
    """
    Emits LLVM TableGen files for all proposed custom instructions.

    Parameters
    ----------
    output_dir : str or Path
        Directory where generated files are written.
    workload_name : str
        Name of the analyzed workload (used in file headers).
    """

    def __init__(
        self,
        output_dir: str = "./output/tablegen",
        workload_name: str = "transformer_workload",
    ):
        self.output_dir = Path(output_dir)
        self.workload_name = workload_name

    def emit(
        self, proposals: List[Tuple[HotspotResult, CustomInstruction]]
    ) -> List[Path]:
        """
        Emit all TableGen files for the given proposals.

        Returns list of paths to generated files.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        generated = []

        # Main instruction definitions file
        td_path = self.output_dir / "RISCVInstrInfoCustom.td"
        self._write_instr_td(td_path, proposals)
        generated.append(td_path)

        # ISel DAG patterns file
        pat_path = self.output_dir / "RISCVCustomInstrPatterns.td"
        self._write_patterns_td(pat_path, proposals)
        generated.append(pat_path)

        # CMakeLists integration note
        cmake_path = self.output_dir / "CMakeLists_integration.txt"
        self._write_cmake_note(cmake_path)
        generated.append(cmake_path)

        # Per-instruction summary JSON
        import json
        summary_path = self.output_dir / "instructions_summary.json"
        summary = {
            "generated": datetime.now().isoformat(),
            "workload": self.workload_name,
            "instructions": [instr.to_dict() for _, instr in proposals],
        }
        summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        generated.append(summary_path)

        logger.info("TableGen: emitted %d files to %s", len(generated), self.output_dir)
        return generated

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _write_instr_td(
        self,
        path: Path,
        proposals: List[Tuple[HotspotResult, CustomInstruction]],
    ) -> None:
        lines = [
            _HEADER.format(
                filename=path.name,
                timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                workload_name=self.workload_name,
            )
        ]

        # Declare custom instruction format class if R4 is used
        has_r4 = any(
            instr.instruction_format.value == "R4" for _, instr in proposals
        )
        if has_r4:
            lines.append(self._r4_format_class())

        for hotspot, instr in proposals:
            lines.append(f"// {'-' * 66}")
            lines.append(f"// Instruction: {instr.mnemonic.upper()}")
            lines.append(f"// Accelerates: {instr.target_op_type}")
            if instr.speedup_model:
                lines.append(
                    f"// Est. speedup: {instr.speedup_model.estimated_speedup:.1f}x"
                )
            lines.append(f"// {'-' * 66}")
            lines.append("")
            lines.append(instr.tablegen_snippet)
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.debug("Wrote %s", path)

    def _write_patterns_td(
        self,
        path: Path,
        proposals: List[Tuple[HotspotResult, CustomInstruction]],
    ) -> None:
        lines = [
            _HEADER.format(
                filename=path.name,
                timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                workload_name=self.workload_name,
            ),
            "// ISel DAG patterns for custom instructions",
            "// These patterns tell LLVM when to emit each custom instruction.",
            "// Extend these with intrinsic-based patterns for full codegen support.",
            "",
        ]

        for hotspot, instr in proposals:
            mnem = instr.mnemonic.replace(".", "_").upper()
            lines.append(f"// Pattern for {mnem}")
            lines.append(
                f"// def : Pat<(int_riscv_{mnem.lower()} GPR:$rs1, GPR:$rs2),\n"
                f"//           ({mnem} GPR:$rs1, GPR:$rs2)>;"
            )
            lines.append(
                f"// Uncomment and customize after defining the corresponding intrinsic."
            )
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    def _write_cmake_note(self, path: Path) -> None:
        content = """\
CMakeLists.txt Integration Note
================================
To include the custom instruction definitions in your LLVM RISCV backend build:

1. Copy RISCVInstrInfoCustom.td and RISCVCustomInstrPatterns.td to:
   llvm/lib/Target/RISCV/

2. Edit llvm/lib/Target/RISCV/RISCVInstrInfo.td and add near the top:
   include "RISCVInstrInfoCustom.td"

3. If using ISel patterns, also add:
   include "RISCVCustomInstrPatterns.td"

4. Rebuild LLVM:
   cd llvm-build/
   cmake --build . --target llc -j$(nproc)

5. Verify the new instructions are recognized:
   llc -march=riscv32 -mattr=+m,+f,+custom -o /dev/null /dev/null

Notes:
- These instructions use custom-0 (0x0B), custom-1 (0x2B), custom-2 (0x5B) opcode spaces.
- Ensure no encoding conflicts with any other custom extensions in your toolchain.
- For full compiler integration, define LLVM intrinsics in:
  llvm/include/llvm/IR/IntrinsicsRISCV.td
"""
        path.write_text(content, encoding="utf-8")

    @staticmethod
    def _r4_format_class() -> str:
        return """\
// R4-type instruction format (for 4-operand custom instructions)
// Encoding: [rs3(5)|funct2(2)|rs2(5)|rs1(5)|funct3(3)|rd(5)|opcode(7)]
class RVInstR4Custom<bits<2> funct2, bits<3> funct3, bits<7> opcode,
                     dag outs, dag ins, string opcodestr, string argstr>
    : RVInst<outs, ins, opcodestr, argstr, [], InstFormatOther> {
  bits<5> rs3;
  bits<5> rs2;
  bits<5> rs1;
  bits<5> rd;
  let Inst{31-27} = rs3;
  let Inst{26-25} = funct2;
  let Inst{24-20} = rs2;
  let Inst{19-15} = rs1;
  let Inst{14-12} = funct3;
  let Inst{11-7}  = rd;
  let Inst{6-0}   = opcode;
  let mayLoad = 1;
  let mayStore = 1;
}

"""
